# Generates graphviz file from the compose.awk output
# loriacarlos@gmail.com
# compose_output/composed_plan.txt --> gv_output/study_plan.gv
# To run
# awk -f gengraph.awk compose_output/composed_plan.txt > gv_output/study_plan.gv

BEGIN {
    FS="::";
    course_regex = /(^EIF|^MAY)/;
	print "digraph Plan {";
}

# Expected input record format generated by compose
# nn::code::description::[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)

{
    printf "    %s -> %s;\n", $5, $2;
    courseField = 6;
    while ($courseField ~ course_regex) {
        printf "    %s -> %s;\n", $courseField, $2;
        courseField++;
    }
}

END {
	print "}\n";
}
