# Generates prolog file from compose.awk output
# loriacarlos@gmail.com
# compose_output/composed_plan.txt --> prolog_output/study_plan.pl
# To run
# awk -f src/genprolog.awk compose_output/composed_plan.txt > prolog_output/study_plan.pl

BEGIN {
	FS="::";
    opt_regex = /(EI(F|G)[0-9][0-9][0-9]O)/;
    print "%%%%% Study Plan %%%%%";
    print ":- discontiguous course/1.";
    print ":- discontiguous course/8.";
    print ":- discontiguous course_req/2";
}

# Expected input record format generated by compose
# nn::code::description::credits[2345](::req)*::(bsc|dipl)::(level|_)::(cycle|_)
# req ~ EI(F|G)...O? | LIX...

{
    printf "%% --- '%s' ---\n", $2;
    printf "course('%s').\n", $2;

    # To check the type of course
    course_type = "regular";
    if ($2 ~ /EI(F|G)[0-9][0-9][0-9]O/) {
        course_type = "optional";
    }
    if ($2 ~ /Optativa/) {
        course_type = "generic";
    }

    # Last field stores the course cycle
    last_field = NF;
    year = 1;
    cycle = 1;

    if (course_type == "optional")
    # Find the current course cycle
    if ($last_field == "II") {
        cycle = 2;
    }
    if ($last_field == "_") {
        cycle = "none";
    }

    last_field--;   # Now work with the year field (N - 1)
    # Find the current course year
    if ($last_field == "II") {
        year = 2;
    }
    if ($last_field == "III") {
        year = 3;
    }
    if ($last_field == "IV") {
        year = 4;
    }
    if ($last_field == "_") {
        year = "none";
    }

    printf "course('%s', %s, %s, %s, %s, %s, %s, '%s' ).\n", $2, $1, course_type, $6, $4, year, cycle, $3;

    courseField = 5;
    while ($courseField ~ /(^EIF|^MAY|^LIX|Admission)/) {
        printf "course_req('%s', '%s').\n", $2, $courseField;
        courseField++;
    }
}


END {
}
